image: node:16

stages:
  - container
  - deploy

build_image:
  image: docker:latest
  stage: container
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: '/certs'
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --build-arg SPEAKEASY_VER=$CI_COMMIT_REF_NAME --no-cache -t docker-registry.xx.network/elixxir/speakeasy-web:$CI_COMMIT_REF_NAME .
    - docker push docker-registry.xx.network/elixxir/speakeasy-web:$CI_COMMIT_REF_NAME
  only:
    - staging
    - dev
    - backend-dev
    - tags
  tags:
    - dind
